### PR TITLE
Store release information in public

### PR DESCRIPTION
**Pull request by matsduf**
## Purpose

Add release information to the public document path. **This PR is not to be merged.** It is to show a proposal that would be executed at an upcoming release for that release.

File "public/RELEASE.md" is added. The file should be updated at release time with the release information of the latest release (and not including previous releases). The content is to be directly copied to the Github release page, e.g. https://github.com/zonemaster/zonemaster/releases/tag/v2023.2.1. No edits should be needed.

SUMMARY.md has also been updated with a link to the RELEASE.md file.

I built a "book" and the file works well into the book.

## How to test this PR

Review. Build a "book" following the instruction in https://github.com/zonemaster/zonemaster?tab=readme-ov-file#documentation.

### CODE REVIEW

**Comment by mattias-p** [comment]
This looks really nice.

Perhaps rename RELEASE.md to RELEASES.md and keep a history of all releases in the same file, or of all releases up to a certain point (e.g. v2023.2.1 and newer). I'm not sure if there's huge value in this but it just feels a bit weird to me to remove the details of the last release every time we make a new one.

**Comment by matsduf** [comment]
My idea is exactly to keep only the latest release notes in the file, and refer to Github release notes for previous releases. Then the content will be exactly the same as is entered in Github, and the focus will be on the latest release.

**Comment by mattias-p** [comment]
Fair enough, I reckoned as much. I had a different idea and I wanted to raise it.

**Review by marc-vanderwal — APPROVED** [review]

**Review by mattias-p — APPROVED** [review]
I don't believe I've ever seen a software project that maintains a file with information about the current release only. The way people seem to go about things is to keep a proper change log where you can search the entire change history back to the inception of the file using basic tools.  Since we're deviating from this for no apparent reason I feel we're being a bit weird. But having a RELEASE file is better than not having one.

**Comment by matsduf** [comment]
> I don't believe I've ever seen a software project that maintains a file with information about the current release only. The way people seem to go about things is to keep a proper change log where you can search the entire change history back to the inception of the file using basic tools. Since we're deviating from this for no apparent reason I feel we're being a bit weird. But having a RELEASE file is better than not having one.

In the release file there is a link to the historic Changes. The idea with this file is that it should be in the top of the documentation and then a complete file would be too long. Now we have the information for one release. We can discuss it later when we see how it looks like.

**Comment by matsduf** [comment]
This PR has fullfilled is purpose and can be closed now.

**Pull request closed without merging**
