### PR TITLE
Updated translation status in README

### PR DESCRIPTION
**Pull request by matsduf**
* Updated translation status
* Updated database versions
* Updated "notable bugs and issues"

### CODE REVIEW

**Comment by sandoche2k** [comment]
@matsduf for CentOS 8, the PSQL versions available are 9.6, 10 and 12
For translation, it works for CLI for both CentOS 7 & 8
Same from the GUI. If it works in the GUI, then the backend should be Ok, Isn't it ?

**Comment by matsduf** [comment]
> @matsduf for CentOS 8, the PSQL versions available are 9.6, 10 and 12

Which version has been tested? The installation instruction says 9.3.

> For translation, it works for CLI for both CentOS 7 & 8
> Same from the GUI. If it works in the GUI, then the backend should be Ok, Isn't it ?

Yes.

**Comment by mattias-p** [comment]
I've successfully tested translation for both CLI and Backend on both Debian 9 and Debian 10.

**Comment by matsduf** [comment]
@sandoche2k, the README is not complete since I need the information on what databases and versions that you have tested. (It must also match the installation instruction.)

**Comment by sandoche2k** [comment]
For CentOS7 it is 9.3 (which was forced by me) and for CentOS 8, by default it is 10.6

**Pull request merged**
