### PR TITLE
Clarify MethodsV2?

### PR DESCRIPTION
**Pull request by matsduf**
## Purpose

This PR makes it explicit that CNAME should be followed. Does this match the implementation

## How to test this PR

Review the change and judge if the change is desired and if it matches the implementation.

### CODE REVIEW

**Comment by marc-vanderwal** [comment]
In this context, we are resolving A and AAAA resource records for names that we found in NS records, right? Yet, [RFC 2181, § 10.3](https://datatracker.ietf.org/doc/html/rfc2181#section-10.3) disallows pointing to an alias from an NS record. If anything, Zonemaster should report an error in this situation, instead of following CNAMEs.

**Comment by matsduf** [comment]
> Yet, [RFC 2181, § 10.3](https://datatracker.ietf.org/doc/html/rfc2181#section-10.3) disallows pointing to an alias from an NS record. If anything, Zonemaster should report an error in this situation, instead of following CNAMEs.

It is correct that the hostname in the RDATA of an NS record must not have a CNAME record, and Bind will not follow a CNAME. This is the method collecting as many name servers for the zone as possible to be able report as many issues as possible. The methods do not report any issues at all. That is up to the test cases to do.

[Delegation05] checks if the name server names has a CNAME record, and if so outputs `NS_IS_CNAME` on `ERROR` level

[Delegation05]: https://github.com/zonemaster/zonemaster/blob/master/docs/public/specifications/tests/Delegation-TP/delegation05.md

**Comment by marc-vanderwal** [comment]
Okay, then I understand the rationale. I’d just suggest adding a remark on why Zonemaster follows aliases in that specific case, even though NS records aren’t supposed to point to any. Then it should be fine.

**Comment by matsduf** [comment]
A clarification of the resolution of  CNAME has been added. @marc-vanderwal @tgreenx, please re-review.

**Review by marc-vanderwal — APPROVED** [review]

**Comment by matsduf** [comment]
@tgreenx, can I just merge? Is any update in the implementation needed?

**Pull request merged**
