### PR TITLE
Updated Report.md

### PR DESCRIPTION
**Pull request by matsduf**
Report generated with an updated tool (see #659 ) based on what is in the develop branch. The file is incomplete because some files have not been updated correctly. When the develop branch is updated with relevant data, this PR will be updated.

### CODE REVIEW

**Comment by sandoche2k** [comment]
@matsduf i can see the last three new test cases has not been updated. But i do not see any difference between R84 which has been updated.

**Comment by matsduf** [comment]
@sandoche2k, I'm sorry, I do not understand what you mean by "i do not see any difference between R84 which has been updated".

**Comment by sandoche2k** [comment]
The three test requirements i have added has been updated in the same manner as R84. R84 has been identified by the tool, while the other three test requirements were not.

**Comment by matsduf** [comment]
The test plan readme file has to be updated too. I will fix a PR on that.

**Comment by sandoche2k** [comment]
@matsduf pls. merge

**Pull request merged**
