### PR TITLE
First version of Test Case Specification Status

### PR DESCRIPTION
**Pull request by matsduf**
## Purpose

The test case specification format has evolved to more explicit. This PR adds an internal document that will show the status of the specifications and gives an overview of the status.

This must be updated when specifications are updated or added.

### CODE REVIEW

**Review by tgreenx — DISMISSED** [review]
Thanks Mats, it will be an useful document for future tracking of test specification updates.

**Comment by tgreenx** [comment]
Moreover, I think it would be useful to add another column regarding the use of [MethodsNT](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/MethodsNT.md).

**Comment by matsduf** [comment]
> Moreover, I think it would be useful to add another column regarding the use of [MethodsNT](https://github.com/zonemaster/zonemaster/blob/master/docs/specifications/tests/MethodsNT.md).

Good suggestion. I have added that in the Tracking Issue that I moved the document to (#1051).

**Comment by matsduf** [comment]
The content of this PR has been moved to an issue of a special type, a Tracking Issue. See #1051.

**Pull request closed without merging**
